import {
  BookOpen,
  BrainCircuit,
  CalendarRange,
  CircleHelp,
  ClipboardList,
  FileCheck2,
  Layers3,
  ListChecks,
  Mail,
  ScrollText,
  Sparkles,
  Target,
} from 'lucide-react';

export const TOOL_ICONS = Object.freeze({
  explain: BrainCircuit,
  summarize: BookOpen,
  plan: CalendarRange,
  quiz: CircleHelp,
  flashcards: Layers3,
  research: Target,
  email: Mail,
  tasks: ListChecks,
  meeting: ClipboardList,
  cv: FileCheck2,
  cover: ScrollText,
  qa: ClipboardList,
  ask: Sparkles,
  rewrite: FileCheck2,
  brainstorm: BrainCircuit,
  decide: ListChecks,
  organize: CalendarRange,
  content: BookOpen,
});
